// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdzfffutbzpevblbpgjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkemZmZnV0YnpwZXZibGJwZ2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxMTU1MjcsImV4cCI6MjA4MjY5MTUyN30.vVtAQqmomGP22geTnAD1hrZK1cOdtPQH4O6XW9-rHQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});